### PR TITLE
feat: 🎸 Cookbook Onboard (AI Assistant & Playground) integration

### PR DESCRIPTION
**Pull request by ClockRide**
Cookbook Onboard (AI Assistant & Playground) integration

### Preview
Preview link: https://berachain-docs-cookbook.vercel.app/

### Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Berachain resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building on Berachain, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Berachain-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image
  

### Cookbook Onboard Playground
The Cookbook Onboard Playground embeds a Solidity IDE with smart contract templates displayed alongside the Ask Cookbook AI Assistant.

Developers can search for and deploy Cookbook’s entire smart contract library from your technical documentation.

Features:
- Deploy smart contracts or entire protocols to Berachain without leaving the docs
- Acts as a free, no-code or low-code token and NFT launchpad
- Save source code as a Foundry, Hardhat, or Scaffold project or export it to Remix or Chain IDE in one click

image

## Contribution

- [x] I have followed the [Development Workflow](https://github.com/berachain/docs/blob/main/CONTRIBUTING.md#development-workflow)
- [x] I have read the [CODE OF CONDUCT](https://github.com/berachain/docs/blob/main/CODE_OF_CONDUCT.md)

Let us know your wallet address/ENS:

```
0x07590a393C67670463b80768fEED264832541d51
```

### CODE REVIEW

**Comment by codingwithmanny** [comment]
@ClockRide can you enable this so I can add the fixes.
Screenshot 2024-09-06 at 6 05 22 AM

**Comment by ClockRide** [comment]
> @ClockRide can you enable this so I can add the fixes.
> 
> Screenshot 2024-09-06 at 6 05 22 AM
> 
> 

Don't have this button for some reason. I've invited you as an outside collaborator though

**Comment by codingwithmanny** [comment]
@ClockRide it's typically when you create the PR, but not sure you can edit it afterwards.
Screenshot 2024-09-06 at 7 29 00 AM

**Comment by codingwithmanny** [comment]
Should be able to see it here in the PR @ClockRide 
Screenshot 2024-09-06 at 7 31 06 AM

**Comment by ClockRide** [comment]
> Should be able to see it here in the PR @ClockRide Screenshot 2024-09-06 at 7 31 06 AM

It seems to be impossible for repos owned by organizations, see https://github.com/orgs/community/discussions/5634
image

I've invited you to the repo though with full write access, so feel free to just accept an invite and do changes necessary

**Review by codingwithmanny — APPROVED** [review]
LGTM

**Pull request merged**
